"""clean_schema_sync

Revision ID: 3674eb1fc071
Revises: 8cdc75f87f63
Create Date: 2026-04-13 23:34:38.230436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3674eb1fc071'
down_revision: Union[str, Sequence[str], None] = '8cdc75f87f63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'status')
    op.add_column('applications', sa.Column('status', sa.Enum('PENDING', 'APPLIED', 'SCREENED', 'INTERVIEW', 'OFFERED', 'REJECTED', name='applicationstatus'), nullable=True))
    op.alter_column('applications', 'notes',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_applications_job_id'), 'applications', ['job_id'], unique=False)
    op.drop_constraint(op.f('applications_user_id_fkey'), 'applications', type_='foreignkey')
    op.drop_constraint(op.f('applications_job_id_fkey'), 'applications', type_='foreignkey')
    op.create_foreign_key(None, 'applications', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'applications', 'jobs', ['job_id'], ['id'])
    op.drop_column('applications', 'job_title')
    op.drop_column('applications', 'last_updated')
    op.drop_column('applications', 'company')
    op.alter_column('jobs', 'apply_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('jobs', 'source',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('jobs', 'external_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_jobs_embedding'), table_name='jobs', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_index(op.f('ix_jobs_external_id'), 'jobs', ['external_id'], unique=True)
    op.alter_column('users', 'is_premium',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('users', 'is_premium',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_jobs_external_id'), table_name='jobs')
    op.create_index(op.f('idx_jobs_embedding'), 'jobs', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.alter_column('jobs', 'external_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('jobs', 'source',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('jobs', 'apply_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.add_column('applications', sa.Column('company', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('applications', sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('applications', sa.Column('job_title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.create_foreign_key(op.f('applications_job_id_fkey'), 'applications', 'jobs', ['job_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('applications_user_id_fkey'), 'applications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_applications_job_id'), table_name='applications')
    op.alter_column('applications', 'notes',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('applications', 'status',
               existing_type=sa.Enum('PENDING', 'APPLIED', 'SCREENED', 'INTERVIEW', 'OFFERED', 'REJECTED', name='applicationstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               existing_server_default=sa.text("'Applied'::character varying"))
    # ### end Alembic commands ###
