"""add extracted_data to resumes

Revision ID: 5f1f6722d350
Revises: 340e5b453285
Create Date: 2026-04-25 00:06:26.157434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f1f6722d350'
down_revision: Union[str, Sequence[str], None] = '340e5b453285'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_results', sa.Column('ai_analysis', sa.JSON(), nullable=True))
    op.add_column('resumes', sa.Column('extracted_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'extracted_data')
    op.drop_column('match_results', 'ai_analysis')
    # ### end Alembic commands ###
