"""resume_file_url

Revision ID: 9dbf497ac509
Revises: 3674eb1fc071
Create Date: 2026-04-13 23:43:15.496530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dbf497ac509'
down_revision: Union[str, Sequence[str], None] = '3674eb1fc071'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Since we are moving from local files to S3/Supabase cloud URLs, 
    # we truncate the existing local-only resumes as their paths will be invalid.
    op.execute('TRUNCATE TABLE resumes CASCADE')
    op.add_column('resumes', sa.Column('file_url', sa.String(), nullable=False))
    op.drop_column('resumes', 'file_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('resumes', 'file_url')
    # ### end Alembic commands ###
