"""add_ai_credits_to_user

Revision ID: df5d49caf0fd
Revises: 9dbf497ac509
Create Date: 2026-04-13 23:53:49.799239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df5d49caf0fd'
down_revision: Union[str, Sequence[str], None] = '9dbf497ac509'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ai_credits', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ai_credits')
    # ### end Alembic commands ###
