"""Add trial fields to users and DEMO status to applications

Revision ID: f7204e4a3231
Revises: df5d49caf0fd
Create Date: 2026-04-18 02:25:28.018429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7204e4a3231'
down_revision: Union[str, Sequence[str], None] = 'df5d49caf0fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('trial_used', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('trial_remaining', sa.Integer(), nullable=True))
    
    # Manually add the DEMO status to the enum type
    # Using commit hash to avoid issues with concurrent transactions on some DBs
    op.execute("COMMIT")
    op.execute("ALTER TYPE applicationstatus ADD VALUE 'Demo'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'trial_remaining')
    op.drop_column('users', 'trial_used')
    # ### end Alembic commands ###
